config/routes.rb
EveApps::Application.routes.draw do
  resources :inv_types

  resources :apps

end

app/models/app.rb
class App < ActiveRecord::Base
end

app/models/inv_type.rb
class InvType < ActiveRecord::Base
end

app/controllers/application_controller.rb
require 'net/http'
require 'rexml/document'

class ApplicationController < ActionController::Base
  helper_method :update_values
  protect_from_forgery

  def update_values(types)
    inv_types = InvType.find_all_by_type_id(types.sort)

    types = inv_types.collect do |type|
      type.type_id if Time.now - 1.day > type.updated_at or not type.buy
    end.flatten.compact

    @updates = types.length

    if @updates > 0
      url = [
        'http://api.eve-central.com/api/marketstat?typeid=',
        types.join('&typeid='),
        '&usesystem=',
        30000142
      ].join

      sell = Array.new
      buy = Array.new
      
      data = Net::HTTP.get_response(URI.parse(url)).body
      REXML::Document.new(data).elements.each('/evec_api/marketstat/type/sell/min') do |item|
        sell << item.to_s.gsub(/[^0-9\.]/, '').to_f
      end
      REXML::Document.new(data).elements.each('/evec_api/marketstat/type/buy/max') do |item|
        buy << item.to_s.gsub(/[^0-9\.]/, '').to_f
      end

      sell.each_index do |i|
        type = InvType.find_by_type_id(types[i])
        type.sell = sell[i]
        type.buy = buy[i]
        type.save
      end
    end
  end
end

app/controllers/apps_controller.rb
class AppsController < ApplicationController
  before_filter :find_app, :only => [:show, :edit, :update, :destroy]

  def index
    @apps = App.all
  end

  def show
    case @app.id
      when 1
        @types = [34,35,36,37,38,39,40]
        @inputs = {
          22 => 'Arkonor',
          1223 => 'Bistot',
          1225 => 'Crokite',
          1232 => 'Dark Ochre',
          1229 => 'Gneiss',
          21 => 'Hedbergite',
          1231 => 'Hemorphite',
          1226 => 'Jaspet',
          20 => 'Kernite',
          1227 => 'Omber',
          18 => 'Plagioclase',
          1224 => 'Pyroxeres',
          1228 => 'Scordite',
          19 => 'Spodumain',
          1230 => 'Veldspar'
        }

      when 2
        @types = [38,39,40,30309,30310,30311,30375,30376,30377,30370,30378,30371,30372,30373,30374]
        @inputs = {
          30375 => 'Fullerite-C28',
          30376 => 'Fullerite-C32',
          30377 => 'Fullerite-C320',
          30370 => 'Fullerite-C50',
          30378 => 'Fullerite-C540',
          30371 => 'Fullerite-C60',
          30372 => 'Fullerite-C70',
          30373 => 'Fullerite-C72',
          30374 => 'Fullerite-C84'
        }
      else @inputs = { }
    end
    update_values(@types)
  end

  def new
    @app = App.new
  end

  # def edit

  def create
    @app = App.new(params[:app])

    if @app.save
      redirect_to(@app, :notice => 'App was successfully created.')
    else
      render :action => :new
    end
  end

  def update
    if @app.update_attributes(params[:app])
      redirect_to(@app, :notice => 'App was successfully updated.')
    else
      render :action => :edit
    end
  end

  def destroy
    @app.destroy

    redirect_to(apps_url)
  end

  private
  def find_app
    @app = App.find(params[:id])
  end
end

app/controllers/inv_types_controller.rb
class InvTypesController < ApplicationController
  # GET /inv_types
  # GET /inv_types.xml
  def index
    @inv_types = InvType.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @inv_types }
    end
  end

  # GET /inv_types/1
  # GET /inv_types/1.xml
  def show
    @inv_type = InvType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @inv_type }
    end
  end

  # GET /inv_types/new
  # GET /inv_types/new.xml
  def new
    @inv_type = InvType.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @inv_type }
    end
  end

  # GET /inv_types/1/edit
  def edit
    @inv_type = InvType.find(params[:id])
  end

  # POST /inv_types
  # POST /inv_types.xml
  def create
    @inv_type = InvType.new(params[:inv_type])

    respond_to do |format|
      if @inv_type.save
        format.html { redirect_to(@inv_type, :notice => 'Inv type was successfully created.') }
        format.xml  { render :xml => @inv_type, :status => :created, :location => @inv_type }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @inv_type.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /inv_types/1
  # PUT /inv_types/1.xml
  def update
    @inv_type = InvType.find(params[:id])

    respond_to do |format|
      if @inv_type.update_attributes(params[:inv_type])
        format.html { redirect_to(@inv_type, :notice => 'Inv type was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @inv_type.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /inv_types/1
  # DELETE /inv_types/1.xml
  def destroy
    @inv_type = InvType.find(params[:id])
    @inv_type.destroy

    respond_to do |format|
      format.html { redirect_to(inv_types_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/apps_helper.rb
module AppsHelper
  def generate_json(types)
    update = false
    types.each do |type|
      unless InvType.find_by_type_id type
        InvType.create!(:type_id => type)
        update = true
      end
    end
    update_values(types) if update

    InvType.find_all_by_type_id(types).collect do |type|
  "#{type.type_id}: {
    volume: #{type.volume || 0},
    buy: #{type.buy || 0},
    sell: #{type.sell || 0}
  },
  "
    end.join
  end
end

app/helpers/inv_types_helper.rb
module InvTypesHelper
end

app/views/apps/_form.html.erb
<%= form_for(@app) do |f| %>
  <% if @app.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@app.errors.count, "error") %> prohibited this app from being saved:</h2>

      <ul>
      <% @app.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/apps/edit.html.erb
<h1>Editing app</h1>

<%= render 'form' %>

<%= link_to 'Show', @app %> |
<%= link_to 'Back', apps_path %>

app/views/apps/index.html.erb
<h1>Listing apps</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @apps.each do |app| %>
  <tr>
    <td><%= app.name %></td>
    <td><%= link_to 'Show', app %></td>
    <td><%= link_to 'Edit', edit_app_path(app) %></td>
    <td><%= link_to 'Destroy', app, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New App', new_app_path %>

app/views/apps/new.html.erb
<h1>New app</h1>

<%= render 'form' %>

<%= link_to 'Back', apps_path %>

app/views/apps/show.html.erb
<h1><%= @app.name %></h1>

<%= "#{@updates} updates." if @updates > 0 %>

<div class="form">
  <%= form_tag @app, :method => :get do %>

    <% @inputs.each_pair do |key, value| %>
      <img src="http://image.eveonline.com/InventoryType/<%= key %>_32.png" />
      <%= text_field_tag "type_#{key}", value, :class => 'inactive' %>
    <% end %>

    <%= submit_tag 'Compute' %>

  <% end %>
</div>

<% if @app.id == 1 %>

<div class="category">
  <table>
    <thead>
      <tr>
        <th>Ore</th>
        <th class="value msup3" id="ore">0.0</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>Volume</td>
        <td class="value msup3" id="volume">0.0</td>
      </tr>
      <tr>
        <td>Hauling</td>
        <td class="value s" id="haul_time">0.0</td>
      </tr>
      <tr>
        <td style="color: red;">Buy value</td>
        <td class="value isk" id="ore_buy">0.00</td>
      </tr>
      <tr>
        <td style="color: red;">Sell value</td>
        <td class="value isk" id="ore_sell">0.00</td>
      </tr>
    </tbody>
  </table>
</div>

<div class="category">
  <table>
    <thead>
      <tr>
        <th>Minerals</th>
        <th class="value isk" id="minerals">0.00</th>
      </tr>
    </thead>
    <tbody>
      <% InvType.find_all_by_type_id(34..40).each do |mineral| %>
        <tr>
          <td><%= mineral.name %></td>
          <td class="value" id="type_<%= mineral.type_id %>">0</td>
        </tr>
      <% end %>
      <tr>
        <td>Volume</td>
        <td class="value msup3" id="refine_volume">0.0</td>
      </tr>
      <tr>
        <td>Unrefinable</td>
        <td class="value msup3" id="refine_excess">0.0</td>
      <tr>
      <tr>
        <td>Dodixie sell</td>
        <td class="value isk" id="refine_sell">0.00</td>
      </tr>
      <tr class="default">
        <td>Dodixie buy</td>
        <td class="value isk" id="refine_buy">0.00</td>
      </tr>
    </tbody>
  </table>
</div>

<div class="category">
  <table>
    <thead>
      <tr>
        <th>Mining</th>
        <th class="value hrs" id="mining">0.0</th>
      </tr>
    </thead>
    <tbody>
      <tr class="default">
        <td style="color: yellow;">Time (150k m&sup3;/h)</td>
        <td class="value hrs" id="mining_time">0.0</td>
      </tr>
      <tr>
        <td style="color: yellow;">Sell / hour</td>
        <td class="value isk" id="mining_sell">0.00</td>
      </tr>
      <tr>
        <td style="color: yellow;">Buy / hour</td>
        <td class="value isk" id="mining_buy">0.00</td>
      </tr>
    </tbody>
  </table>
</div>

<div class="category">
  <table>
    <thead>
      <tr>
        <th>Compression</th>
        <th class="value msup3" id="compression">0.0</th>
      </tr>
    </thead>
    <tbody>
      <tr class="default">
        <td style="color: red;">Volume</td>
        <td class="value msup3" id="compression_volume">0.0</td>
      </tr>
      <tr>
        <td>Excess</td>
        <td class="value msup3" id="compression_excess">0.0</td>
      </tr>
      <tr>
        <td style="color: red;">Time</td>
        <td class="value s" id="compression_time">0.00</td>
      </tr>
      <tr>
        <td style="color: red;">Heavy Water</td>
        <td class="value" id="compression_heavy_water">0</td>
      </tr>
      <tr>
        <td style="color: red;">Strontium</td>
        <td class="value" id="compression_strontium_clathrates">0</td>
      </tr>
      <tr>
        <td style="color: red;">Expenses</td>
        <td class="value isk" id="compression_expenses">0.00</td>
      </tr>
    </tbody>
  </table>
</div>

<div class="category">
  <table>
    <thead>
      <tr>
        <th>POS Refining</th>
        <th class="value s">0.0</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td style="color: red;">35%</td>
        <td class="value s" id="refining_standard">0.00</td>
      </tr>
      <tr>
        <td style="color: red;">75%</td>
        <td class="value s" id="refining_medium">0.00</td>
      </tr>
      <tr class="default">
        <td style="color: red;">75%</td>
        <td class="value s" id="refining_intensive">0.00</td>
      </tr>
    </tbody>
  </table>
</div>


<% elsif @app.id == 2 %>
<!-- @types = [30375,30376,30377,30370,30378,30371,30372,30373,30374] -->

<div class="category">
  <table>
    <thead>
      <tr>
        <th>Gas</th>
        <th class="value isk" id="gas">0.0</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td style="color: red;">Volume</td>
        <td class="value msup3" id="volume">0.0</td>
      </tr>
      <tr>
        <td style="color: red;">Hauling</td>
        <td class="value s" id="haul_time">0.0</td>
      </tr>
      <tr class="default">
        <td>Buy value</td>
        <td class="value isk" id="gas_buy">0.00</td>
      </tr>
      <tr>
        <td style="color: red;">Sell value</td>
        <td class="value isk" id="gas_sell">0.00</td>
      </tr>
    </tbody>
  </table>
</div>

<div class="category">
  <table>
    <thead>
      <tr>
        <th>Reservoirs</th>
        <th class="value isk" id="sites">(Vast) 0.0</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>Barren (3,000 C50 + 1,500 C60)</td>
        <td class="value isk" id="barren">0.0</td>
      </tr>
      <tr>
        <td>Token (3,000 C60 + 1,500 C70)</td>
        <td class="value isk" id="token">0.0</td>
      </tr>
      <tr>
        <td>Minor (3,000 C70 + 1,500 C72)</td>
        <td class="value isk" id="minor">0.0</td>
      </tr>
      <tr>
        <td>Ordinary (3,000 C72 + 1,500 C84)</td>
        <td class="value isk" id="ordinary">0.0</td>
      </tr>
      <tr>
        <td>Sizeable (3,000 C84 + 1,500 C50)</td>
        <td class="value isk" id="sizeable">0.0</td>
      </tr>
      <tr>
        <td>Bountiful (5,000 C28 + 1,000 C32)</td>
        <td class="value isk" id="bountiful">0.0</td>
      </tr>
    </tbody>
  </table>
</div>


<div class="category">
  <table>
    <thead>
      <tr>
        <th>Vast</th>
        <th class="value isk" id="vast">0.0</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>Fullerite-C28</td>
        <td class="value">1,000</td>
      </tr>
      <tr>
        <td>Fullerite-C32</td>
        <td class="value">5,000</td>
      </tr>
      <tr>
        <td>Volume</td>
        <td class="value msup3" id="volume">?</td>
      </tr>
      <tr>
        <td>Harvesting</td>
        <td class="value s" id="volume">?</td>
      </tr>
      <tr>
        <td>Buy value</td>
        <td class="value isk" id="vast_buy">0.00</td>
      </tr>
      <tr class="default">
        <td>Buy value, polymer</td>
        <td class="value isk" id="vast_buy_polymer">0.00</td>
      </tr>
    </tbody>
  </table>
</div>

<div class="category">
  <table>
    <thead>
      <tr>
        <th>Vital</th>
        <th class="value isk" id="vital">0.0</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>Fullerite-C320</td>
        <td class="value">500</td>
      </tr>
      <tr>
        <td>Fullerite-C540</td>
        <td class="value">6,000</td>
      </tr>
      <tr>
        <td>Volume</td>
        <td class="value msup3" id="volume">62,500</td>
      </tr>
      <tr>
        <td>Harvesting</td>
        <td class="value s" id="volume">25,000</td>
      </tr>
      <tr>
        <td>Buy value</td>
        <td class="value isk" id="vital_buy">0.00</td>
      </tr>
      <tr class="default">
        <td>Buy value, polymer</td>
        <td class="value isk" id="vital_buy_polymer">0.00</td>
      </tr>
    </tbody>
  </table>
</div>

<div class="category">
  <table>
    <thead>
      <tr>
        <th>Instrumental</th>
        <th class="value isk" id="instrumental">0.0</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>Fullerite-C320</td>
        <td class="value">6,000</td>
      </tr>
      <tr>
        <td>Fullerite-C540</td>
        <td class="value">500</td>
      </tr>
      <tr>
        <td>Volume</td>
        <td class="value msup3" id="volume">35,000</td>
      </tr>
      <tr>
        <td>Harvesting</td>
        <td class="value s" id="volume">14,000</td>
      </tr>
      <tr>
        <td>Buy value</td>
        <td class="value isk" id="instrumental_buy">0.00</td>
      </tr>
      <tr class="default">
        <td>Buy value, polymer</td>
        <td class="value isk" id="instrumental_buy_polymer">0.00</td>
      </tr>
    </tbody>
  </table>
</div>

<% end %>

app/views/inv_types/_form.html.erb
<%= form_for(@inv_type) do |f| %>
  <% if @inv_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@inv_type.errors.count, "error") %> prohibited this inv_type from being saved:</h2>

      <ul>
      <% @inv_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :type_id %><br />
    <%= f.text_field :type_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :volume %><br />
    <%= f.text_field :volume %>
  </div>
  <div class="field">
    <%= f.label :buy %><br />
    <%= f.text_field :buy %>
  </div>
  <div class="field">
    <%= f.label :sell %><br />
    <%= f.text_field :sell %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/inv_types/edit.html.erb
<h1>Editing inv_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @inv_type %> |
<%= link_to 'Back', inv_types_path %>

app/views/inv_types/index.html.erb
<h1>Listing inv_types</h1>

<table>
  <tr>
    <th>Type</th>
    <th>Name</th>
    <th>Volume</th>
    <th>Buy</th>
    <th>Sell</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @inv_types.each do |inv_type| %>
  <tr>
    <td><%= inv_type.type_id %></td>
    <td><%= inv_type.name %></td>
    <td><%= inv_type.volume %></td>
    <td><%= inv_type.buy %></td>
    <td><%= inv_type.sell %></td>
    <td><%= link_to 'Show', inv_type %></td>
    <td><%= link_to 'Edit', edit_inv_type_path(inv_type) %></td>
    <td><%= link_to 'Destroy', inv_type, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Inv type', new_inv_type_path %>

app/views/inv_types/new.html.erb
<h1>New inv_type</h1>

<%= render 'form' %>

<%= link_to 'Back', inv_types_path %>

app/views/inv_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Type:</b>
  <%= @inv_type.type_id %>
</p>

<p>
  <b>Name:</b>
  <%= @inv_type.name %>
</p>

<p>
  <b>Volume:</b>
  <%= @inv_type.volume %>
</p>

<p>
  <b>Buy:</b>
  <%= @inv_type.buy %>
</p>

<p>
  <b>Sell:</b>
  <%= @inv_type.sell %>
</p>


<%= link_to 'Edit', edit_inv_type_path(@inv_type) %> |
<%= link_to 'Back', inv_types_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EveApps</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :all %>
  <%= javascript_include_tag app_path(@app) + '.js' if @app and not @app.new_record? %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>